<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.0							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.0">
<Header n="matrixIJ_O2">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="matrixIJ_O2">
<SecHeader>
  <MetricTable>
    <Metric i="0" n="PAPI_L2_TCM.[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="2000000"/></Info>
    </Metric>
    <Metric i="1" n="PAPI_L1_TCM (proxy).[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
    <Metric i="2" n="CPUTIME (usec).[0,0]" v="raw" t="nil" show="1" show-percent="1">
      <Info><NV n="units" v="events"/><NV n="period" v="1"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
  </MetricDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/home/jawa/Documents/studies/cad/CAD-COC472/1/3/bin/matrixIJ_O2"/>
    <LoadModule i="103" n="&lt;unknown load module&gt;"/>
    <LoadModule i="107" n="/home/jawa/local/hpctoolkit/lib/hpctoolkit/libhpcrun.so.0.0.0"/>
    <LoadModule i="117" n="/home/jawa/local/hpctoolkit/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="123" n="/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19"/>
    <LoadModule i="127" n="/lib/x86_64-linux-gnu/libc-2.19.so"/>
    <LoadModule i="131" n="/lib/x86_64-linux-gnu/ld-2.19.so"/>
    <LoadModule i="135" n="/home/jawa/local/lib/libpapi.so.5.4.3.0"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="&lt;unknown file&gt;"/>
    <File i="42" n=""/>
    <File i="59" n=""/>
    <File i="79" n=""/>
    <File i="80" n=""/>
    <File i="81" n=""/>
    <File i="104" n="&lt;unknown file&gt;"/>
    <File i="108" n="&lt;unknown file&gt;"/>
    <File i="118" n="&lt;unknown file&gt;"/>
    <File i="124" n="&lt;unknown file&gt;"/>
    <File i="128" n="&lt;unknown file&gt;"/>
    <File i="132" n="&lt;unknown file&gt;"/>
    <File i="136" n="./src/home/jawa/PAPI/papi-5.4.3/src/components/perf_event/perf_event.c"/>
    <File i="139" n="./src/home/jawa/PAPI/papi-5.4.3/src/threads.h"/>
    <File i="151" n="./src/home/jawa/PAPI/papi-5.4.3/src/extras.c"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="41" n="main"/>
    <Procedure i="105" n="&lt;partial call paths&gt;" f="1"/>
    <Procedure i="109" n="itimer_signal_handler"/>
    <Procedure i="111" n="papi_event_handler"/>
    <Procedure i="113" n="hpcrun_trampoline_interior"/>
    <Procedure i="115" n="hpcrun_get_thread_data_local_avail"/>
    <Procedure i="119" n="monitor_signal_handler"/>
    <Procedure i="121" n="&lt;program root&gt;" f="1"/>
    <Procedure i="125" n="&lt;unknown procedure&gt;"/>
    <Procedure i="129" n="&lt;unknown procedure&gt;"/>
    <Procedure i="133" n="&lt;unknown procedure&gt;"/>
    <Procedure i="147" n="mmap_read_head"/>
    <Procedure i="137" n="_pe_dispatch_timer"/>
    <Procedure i="140" n="_papi_hwi_lookup_thread"/>
    <Procedure i="152" n="_papi_hwi_dispatch_overflow_signal"/>
  </ProcedureTable>
  <Info/>
</SecHeader>
<SecCallPathProfileData>
<PF i="2" s="105" l="0" lm="103" f="104" n="105">
<C i="3" s="106" l="0">
<PF i="4" s="129" l="0" lm="127" f="128" n="129">
<C i="5" s="130" l="0">
<PF i="6" s="119" l="0" lm="117" f="118" n="119">
<C i="7" s="120" l="0">
<PF i="8" s="109" l="0" lm="107" f="108" n="109">
<S i="9" s="110" l="0">
<M n="0" v="4e+06"/><M n="1" v="5.68286e+06"/>
</S>
</PF>
</C>
<C i="10" s="120" l="0">
<PF i="11" s="137" l="1952" lm="135" f="136" n="137">
<S i="12" s="138" l="1952">
<M n="2" v="7963"/>
</S>
<S i="13" s="142" l="1967">
<M n="2" v="23945"/>
</S>
<S i="14" s="143" l="1973">
<M n="2" v="7975"/>
</S>
<C i="15" s="144" l="2016">
<PF i="16" s="129" l="0" lm="127" f="128" n="129">
<S i="17" s="130" l="0">
<M n="2" v="87733"/>
</S>
</PF>
</C>
<S i="18" s="145" l="2020">
<M n="2" v="7960"/>
</S>
<C i="19" s="146" l="2029">
<PF i="20" s="129" l="0" lm="127" f="128" n="129">
<S i="21" s="130" l="0">
<M n="2" v="15926"/>
</S>
</PF>
</C>
<S i="22" s="149" l="2067">
<M n="2" v="7971"/>
</S>
<C i="23" s="150" l="2081">
<PF i="24" s="152" l="223" lm="135" f="151" n="152">
<S i="25" s="153" l="223">
<M n="2" v="39855"/>
</S>
<C i="26" s="154" l="349">
<PF i="27" s="111" l="0" lm="107" f="108" n="111">
<C i="28" s="112" l="0">
<PF i="29" s="113" l="0" lm="107" f="108" n="113">
<S i="30" s="114" l="0">
<M n="2" v="7970"/>
</S>
</PF>
</C>
<C i="31" s="112" l="0">
<PF i="32" s="115" l="0" lm="107" f="108" n="115">
<S i="33" s="116" l="0">
<M n="2" v="7971"/>
</S>
</PF>
</C>
<S i="34" s="112" l="0">
<M n="2" v="7985"/>
</S>
</PF>
</C>
</PF>
</C>
<C i="35" s="155" l="2089">
<PF i="36" s="129" l="0" lm="127" f="128" n="129">
<S i="37" s="130" l="0">
<M n="2" v="135551"/>
</S>
</PF>
</C>
<S i="38" s="156" l="2003">
<M n="2" v="7988"/>
</S>
</PF>
<PF i="39" s="140" l="102" lm="135" f="139" n="140">
<C i="40" s="141" l="102">
<PF i="41" s="133" l="0" lm="131" f="132" n="133">
<S i="42" s="134" l="0">
<M n="2" v="39860"/>
</S>
</PF>
</C>
</PF>
<PF i="43" s="147" l="1791" lm="135" f="136" n="147">
<S i="44" s="148" l="1791">
<M n="2" v="7967"/>
</S>
</PF>
</C>
<S i="45" s="120" l="0">
<M n="2" v="933788"/>
</S>
</PF>
</C>
<S i="46" s="130" l="0">
<M n="2" v="7966"/>
</S>
</PF>
</C>
</PF>
<PF i="47" s="121" l="0" lm="117" f="118" n="121">
<C i="48" s="122" l="0">
<PF i="49" s="41" l="0" lm="2" f="3" n="41">
<L i="50" s="42" l="0" f="42">
<C i="51" s="47" l="0">
<PF i="52" s="125" l="0" lm="123" f="124" n="125">
<C i="53" s="126" l="0">
<PF i="54" s="125" l="0" lm="123" f="124" n="125">
<C i="55" s="126" l="0">
<PF i="56" s="129" l="0" lm="127" f="128" n="129">
<C i="57" s="130" l="0">
<PF i="58" s="129" l="0" lm="127" f="128" n="129">
<S i="59" s="130" l="0">
<M n="2" v="7966"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<C i="60" s="50" l="0">
<PF i="61" s="125" l="0" lm="123" f="124" n="125">
<C i="62" s="126" l="0">
<PF i="63" s="125" l="0" lm="123" f="124" n="125">
<C i="64" s="126" l="0">
<PF i="65" s="129" l="0" lm="127" f="128" n="129">
<C i="66" s="130" l="0">
<PF i="67" s="129" l="0" lm="127" f="128" n="129">
<S i="68" s="130" l="0">
<M n="2" v="7958"/>
</S>
</PF>
</C>
</PF>
</C>
</PF>
</C>
</PF>
</C>
<L i="69" s="59" l="0" f="59">
<S i="70" s="60" l="0">
<M n="2" v="60921"/>
</S>
</L>
</L>
<L i="71" s="79" l="0" f="79">
<L i="72" s="80" l="0" f="80">
<L i="73" s="81" l="0" f="81">
<S i="74" s="82" l="0">
<M n="0" v="9.8802e+10"/><M n="1" v="1.40597e+11"/><M n="2" v="8.99943e+08"/>
</S>
</L>
</L>
</L>
</PF>
</C>
</PF>
</SecCallPathProfileData>
</SecCallPathProfile>
</HPCToolkitExperiment>
